module.exports = {
        "login": "cbustamante777duoc",
        "id": 52301057,
        "node_id": "MDQ6VXNlcjUyMzAxMDU3",
        "avatar_url": "https://avatars3.githubusercontent.com/u/52301057?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/cbustamante777duoc",
        "html_url": "https://github.com/cbustamante777duoc",
        "followers_url": "https://api.github.com/users/cbustamante777duoc/followers",
        "following_url": "https://api.github.com/users/cbustamante777duoc/following{/other_user}",
        "gists_url": "https://api.github.com/users/cbustamante777duoc/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/cbustamante777duoc/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/cbustamante777duoc/subscriptions",
        "organizations_url": "https://api.github.com/users/cbustamante777duoc/orgs",
        "repos_url": "https://api.github.com/users/cbustamante777duoc/repos",
        "events_url": "https://api.github.com/users/cbustamante777duoc/events{/privacy}",
        "received_events_url": "https://api.github.com/users/cbustamante777duoc/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Cbustamante777",
        "company": null,
        "blog": "",
        "location": "santiago",
        "email": null,
        "hireable": null,
        "bio": null,
        "public_repos": 20,
        "public_gists": 0,
        "followers": 0,
        "following": 0,
        "created_at": "2019-06-27T23:09:12Z",
        "updated_at": "2020-04-22T22:08:58Z"
      };
      